project:
  type: website
  output-dir: docs
 
website:
  cookie-consent:
    type: express
    style: headline
    palette: dark  
  title: "Casey E. Berger"
  navbar:
    background: primary #color of background is primary color in palette
    search: true
    #left is left-aligned top bar
    left:
      - href: index.qmd
        text: "Home"
      - href: cv_and_pubs.qmd
        text: "CV and Publications"
      - text: "Teaching"
        sidebar:teaching
            
  sidebar:
    #- id: cv_and_pubs
    #  title: "CV and Publications"
    #  background: light
    #  contents:
    #   - cv_and_pubs.qmd
   
    - id: teaching
      title: "Teaching and Pedagogy"
      style: "docked"
      background: light
      contents:
       - teaching_philosophy.qmd
       - inclusive_classroom.qmd
       
 
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual