project:
  type: website
  output-dir: docs
 
website:
  cookie-consent:
    type: express
    style: headline
    palette: dark  
  title: "Casey E. Berger"
  navbar:
    background: primary #color of background is primary color in palette
    search: true
    #left is left-aligned top bar
    left:
      - href: index.qmd
        text: Home
      - sidebar:about
      - sidebar:teaching
      - sidebar:python-data-science
      - sidebar:sds-271-f23
            
  sidebar:
    - id: about
      title: "About Me"
      style: "docked"
      background: light
      contents:
       - bio.qmd
       - cv_and_pubs.qmd
   
    - id: teaching
      title: "Teaching and Pedagogy"
      style: "docked"
      background: light
      contents:
       - teaching_philosophy.qmd
       - inclusive_classroom.qmd
       
    - id: python-data-science
      title: "Data Science in the Physics Classroom"
      style: "docked"
      background: light
      contents:
        - beginning_python.qmd
        - python_data_science.qmd
        
    - id: sds-271-f23
      title: "SDS 271 Fall 2023"
      style: "docked"
      background: light
      contents: 
        - sds-271-f23-homepage.qmd
        - SDS271/F23/Lab1_clean.qmd
        - SDS271/F23/Lab2_clean.qmd
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual