---
title: "CV and Publications"
format: 
  html:
    toc: true
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
    self-contained: true
editor: visual
jupyter: python3
---

# Research-Backed Practices

Traditional lecture-heavy lesson planning is not the most effective way to facilitate student learning. My teaching philosophy incorporates research-backed methods to help students build efficacy and cultivate a set of tools they can use beyond my classroom.

Using research-backed methods in the classroom takes time and effort. It's challenging, and there are [lots of barriers to implementation](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3516788/). But it's worth it.

## Active Learning

Learning is an active process. If I stand in front of the classroom and deliver a perfect lecture, the best case is that students will absorb the information I've provided and be able to regurgitate it later on an exam. But this style of teaching gives the students no opportunities to practice applying that information. Active learning [improves retention of knowledge](https://www.pnas.org/doi/10.1073/pnas.1319030111), and it facilitates the acquisition of a deeper understanding: not just a memorization of facts, but an ability to apply the knowledge in more complex ways.

Active learning is effective not only [at the introductory level](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1305885/), but also in [advanced graduate coursework](https://arxiv.org/abs/2012.03851).

## Building Community

Students benefit greatly from working with their peers. Those who may need a little extra support are able to watch their peers model their thinking process and are likely to share the same questions, which reinforces a growth mindset. Students who are already on top of the material benefit as well, as walking a peer through how they arrived at the answer strengthens their own understanding of the concept and can help reveal nuance. [Groups should be kept small enough that all students are able to contribute](https://www.trevormuir.com/blog/optimal-student-group-size), but [large enough to balance out possible power dynamics](https://www.trevormuir.com/blog/optimal-student-group-size). [The most successful groups have been shown to be around 3-5 students](https://psycnet.apa.org/record/2006-05169-008?doi=1).

But the community is not just between students and their peers: it includes the instructor as well. My practice is to trust my students and to work with them on an individual level. We are all still learning how to learn (even those of us who have been doing this a long time), and taking ownership of your own education is far more valuable than performing well in a classroom with rigid expectations. The trust between student and instructor takes time to develop, but it's essential to supporting students in a way that prepares them for the world outside the classroom.

## Reducing Distractions

Short-term memory is extremely limited. The human brain is built to process information, but it can only handle so much at one time. Every embellishment -- from complicated visuals to interesting side stories -- steals attention away from the concepts being presented and [minimizing the ability of students to absorb the information](https://cwsei.ubc.ca/sites/default/files/cwsei/resources/literature/Cognitive-Load_CWSEI.pdf).

## Concepts First, Jargon Later

Jargon is a useful shorthand. But in order for the shorthand to be effective, the people using the jargon need to understand the underlying concepts.

Jargon is for experts, not learners. Introducing shorthand words -- even if they are standard in the field -- [only obfuscates the concepts](https://iubmb.onlinelibrary.wiley.com/doi/full/10.1002/bmb.20922).

## Safe and Inclusive Classrooms

If students feel unsafe or like they don't belong, their ability to learn and grow will be limited.

There are many things you can do to [make your classroom safer and more inclusive](#inclusive-classroom).
